### PR TITLE
Pass Params to all service calls.

### PR DESCRIPTION
**Pull request by dallinbjohnson**
### Summary

I am wanting to pass all params except provider, and query to all service calls for auth management. This is so the internal call will get all params and custom params for server-side hooks. We need to pass additional params, but the current code is fixed.

### CODE REVIEW

**Comment by fratzinger** [comment]
Great addition!

Other libraries use a simple `passParams`/`makeParams`/`params` function (see [feathers-fletching](https://github.com/DaddyWarbucks/feathers-fletching/blob/master/src/hooks/joinQuery.js#L20)).

I would love to see this in f-a-m. A `passParams` option for the f-a-m service ([these options](https://github.com/feathersjs-ecosystem/feathers-authentication-management/blob/master/docs.md#service)).

To not introduce a breaking change it would be `undefined` per default. Most basic example would look like this:
```js
(defaultParams, context) => defaultParams
```

Your approach would look like this:
```js
(params) => {
  let {provider: _, query: __, ...passedParams} = params;
  return passedParams;
}
```

The advantage would be, that everyone can stretch it to his/her need, even context-based in a function. Maybe it's dependent on a user or permissions or...

@dallinbjohnson what do you think about this?

**Comment by fratzinger** [comment]
Thanks for the changes and nice that you added a test for it.

Could you please make `passParams: undefined` by default? That wouldn't mean a breaking change.

```js
let passedParams = options.passParams && await options.passParams(params);
```

**Comment by dallinbjohnson** [comment]
@fratzinger Is there anything else I need to do to get this approved to be merged?

**Comment by fratzinger** [comment]
Sorry for the delay. If @claustres gives his okay, I'm happy to merge :)

**Comment by claustres** [comment]
I am not really able to follow all changes on the current projects I am involved into so do not hesitate to go ahead, no breaking changes, some tests :+1:

**Pull request merged**
